name: "GitHub Action to add for Pytest and Pytest Coverage Report in GitHub Action Summary"
description: "GitHub action will generate Action's Job Summary report with Pytest details and Pytest-Coverage details."

branding:
  color: "blue"
  icon: "bar-chart"

inputs:
  pytest_results_file:
    description: "Path for pytest results file. This has to be a pytest results file in XML format."
    required: true
  
  pytest_cov_file:
    description: "Path for pytest-coverage report file. This has to be a pytest coverage report file in XML format."
    required: false
    default: "NONE"

  pytest_results_add_to_job_summary:
    description: "Add pytest results to GitHub Action's Job Summary"
    required: false
    default: true

  pytest_cov_add_to_job_summary:
    description: "Add pytest-coverage report to GitHub Action's Job Summary"
    required: false
    default: true

  pytest_cov_failure_threshold:
    description: "Fail the coverage report if coverage percentage is below this threshold."
    required: false
    default: 70


outputs:
  stdout:
    description: "Program stdout"
  stderr:
    description: "Program stderr"
  error:
    description: "A string of 'true' or 'false' that tells if there were errors."

runs:
  using: "composite"
  steps:
    - name: "Extracting the current branch name"
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: "Clone the Repository"
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.extract_branch.outputs.branch }}
        path: repodir

    - name: "Pre-tasks"
      shell: bash
      run: |
        pwd
        echo "=== Inputs ==="
        echo "pytest_results_file -> ${{inputs.pytest_results_file}}"
        echo "pytest_cov_file -> ${{inputs.pytest_cov_file}}"
        echo "pytest_results_add_to_job_summary -> ${{inputs.pytest_results_add_to_job_summary}}"
        echo "pytest_cov_add_to_job_summary -> ${{inputs.pytest_cov_add_to_job_summary}}"
        echo "pytest_cov_failure_threshold -> ${{inputs.pytest_cov_failure_threshold}}"

    - name: "Install Python"
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: "Running the GitHub action for pytest and pytest-cov reports analysis."
      shell: bash
      env:
        PYTEST_pytest_results_file: ${{inputs.pytest_results_file}}
        PYTEST_pytest_cov_file: ${{inputs.pytest_cov_file}}
        PYTEST_pytest_results_add_to_job_summary: ${{inputs.pytest_results_add_to_job_summary}}
        PYTEST_pytest_cov_add_to_job_summary: ${{inputs.pytest_cov_add_to_job_summary}}
        PYTEST_pytest_cov_failure_threshold: ${{inputs.pytest_cov_failure_threshold}}
      run: |
        python -u ${{ github.action_path }}/src/main.py
